# Copyright 2023 The Kubernetes Authors.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}
  labels:
    {{- include "node-ipam-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-manager-role
  labels:
    {{- include "node-ipam-controller.labels" . | nindent 4 }}
rules:
  {{- (.Files.Get "gen/role.yaml" | fromYaml).rules | toYaml | nindent 0}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-rolebinding
  labels:
    {{- include "node-ipam-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "node-ipam-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
{{- if .Values.leaderElection.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["create","get","list"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["update"]
  resourceNames: ["node-ipam-controller"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-ipam-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "node-ipam-controller.serviceAccountName" . }}-leader-election-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}}